all: true
check-coverage: true
include:
  - "src/**/*.js"
exclude:
  - "**/*.test.js"
  - "src/app/debug/"
report-dir: coverage
statements: 70
branches: 80
functions: 80
lines: 70
watermarks:
  statements:
    - 60
    - 90
  branches:
    - 80
    - 90
  functions:
    - 60
    - 90
  lines:
    - 60
    - 90
