all: true
check-coverage: true
include:
  - "src/**/*.js"
exclude:
  - "**/*.test.js"
report-dir: coverage
statements: 10
branches: 10
functions: 10
lines: 20
watermarks:
  statements:
    - 60
    - 90
  branches:
    - 80
    - 90
  functions:
    - 60
    - 90
  lines:
    - 60
    - 90
