name: Docker build and push to ECR
on:
  push:
    branches:
      - PYIC-1018-docker_ecr_build
jobs:
  dockerBuildAndPush:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: test
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
        with:
          fetch-depth: '0'
      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE}
          docker build -t core-front-build:${{ github.sha }} .
          docker tag core-front-build:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/core-front-build:${{ github.sha }}
          docker image ls
      - name: Push docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/core-front-build:${{ github.sha }}